
package SOAP.wsdl.gt.com.tigo.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetBusinessNameSoap", targetNamespace = "http://services.tigo.com.gt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetBusinessNameSoap {


    /**
     * 
     * @param payload
     * @return
     *     returns gt.com.tigo.services.GetBusinessNameResponse
     */
    @WebMethod(operationName = "GetBusinessName", action = "http://services.tigo.com.gt/BusinessName/GetBusinessName")
    @WebResult(name = "GetBusinessNameResponse", targetNamespace = "http://services.tigo.com.gt", partName = "payload")
    public GetBusinessNameResponse getBusinessName(
        @WebParam(name = "GetBusinessNameRequest", targetNamespace = "http://services.tigo.com.gt", partName = "payload")
        GetBusinessNameRequest payload);

}
