
package SOAP.wsdl.gt.com.tigo.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetLocationSoap", targetNamespace = "http://services.tigo.com.gt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetLocationSoap {


    /**
     * 
     * @param payload
     * @return
     *     returns gt.com.tigo.services.VMELocationOutput
     */
    @WebMethod(operationName = "GetLocation", action = "http://services.tigo.com.gt/Client/GetLocation")
    @WebResult(name = "VME_Location_Output", targetNamespace = "http://services.tigo.com.gt", partName = "payload")
    public VMELocationOutput getLocation(
        @WebParam(name = "VME_Location_Input", targetNamespace = "http://services.tigo.com.gt", partName = "payload")
        VMELocationInput payload);

}
