
package SOAP.wsdl.gt.com.tigo.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetLocation", targetNamespace = "http://services.tigo.com.gt", wsdlLocation = "http://172.22.181.139:8011/PortalWholesale/PS/Location?wsdl")
public class GetLocation
    extends Service
{

    private final static URL GETLOCATION_WSDL_LOCATION;
    private final static WebServiceException GETLOCATION_EXCEPTION;
    private final static QName GETLOCATION_QNAME = new QName("http://services.tigo.com.gt", "GetLocation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.22.181.139:8011/PortalWholesale/PS/Location?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETLOCATION_WSDL_LOCATION = url;
        GETLOCATION_EXCEPTION = e;
    }

    public GetLocation() {
        super(__getWsdlLocation(), GETLOCATION_QNAME);
    }

    public GetLocation(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETLOCATION_QNAME, features);
    }

    public GetLocation(URL wsdlLocation) {
        super(wsdlLocation, GETLOCATION_QNAME);
    }

    public GetLocation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETLOCATION_QNAME, features);
    }

    public GetLocation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetLocation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetLocationSoap
     */
    @WebEndpoint(name = "GetLocationSoap")
    public GetLocationSoap getGetLocationSoap() {
        return super.getPort(new QName("http://services.tigo.com.gt", "GetLocationSoap"), GetLocationSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetLocationSoap
     */
    @WebEndpoint(name = "GetLocationSoap")
    public GetLocationSoap getGetLocationSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.tigo.com.gt", "GetLocationSoap"), GetLocationSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETLOCATION_EXCEPTION!= null) {
            throw GETLOCATION_EXCEPTION;
        }
        return GETLOCATION_WSDL_LOCATION;
    }

}
